apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "graph.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "graph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "graph.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name | quote }}-registrykey
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "graph.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "master" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SERVER_PORT
            value: "8000"
          - name: LOG_LEVEL
            value: InfoLevel
          - name: CPU_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}
                resource: requests.cpu
          - name: CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}
                resource: limits.cpu
          - name: MEM_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}
                resource: requests.memory
          - name: MEM_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}
                resource: limits.memory
          - name: MONGO_CONNECTOR
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name | quote }}-mongo
                key: connector
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /playground
              port: http
            failureThreshold: 30
            periodSeconds: 10
          #livenessProbe:
          #  exec:
          #    command:
          #      - curl
          #      - -g
          #      - -X POST
          #      - -H "Content-Type: application/json" \
          #      - -d '{"query":"query{showCollection {items { title firstEpisodeDate lastEpisodeDate henshinMp4 { url }}}}"}' \
          #      http://localhost:8000/query
          #  initialDelaySeconds: 3
          #  periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
